config/routes.rb
Camper::Application.routes.draw do
  resources :places
  resources :services
  resources :gallery_images
    
  devise_for :users

  root :to => 'home#index'
end

app/models/gallery_image.rb
class GalleryImage < ActiveRecord::Base
  attr_accessible :image, :place_id
  belongs_to :place
  
  mount_uploader :image, PlaceImageUploader
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name
  has_many :places

  class << self
    def avaliable_locations_for_select
      all
    end
  end
end

app/models/place.rb
class Place < ActiveRecord::Base
  STATUSES = %w(Draft Published)

  attr_accessible :description, :name, :status, :image, :location_id

  mount_uploader :image, PlaceImageUploader

  has_many :images, class_name: 'PlaceImage'
  has_many :services
  has_many :gallery_images, dependent: :destroy
  belongs_to :location


  def status_to_word
    STATUSES[self.status]
  end

  def services_count
    self.services.count
  end

  def location_name
    if self.location
      self.location.name
    else
      "Not specified"
    end
  end
end

app/models/place_image.rb
class PlaceImage < ActiveRecord::Base
  attr_accessible :image
end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :description, :image, :name, :price, :status, :place_id

  STATUSES = %w(Draft Published Unavailable)
  mount_uploader :image, ServiceImageUploader
  belongs_to :place

  def status_name
    STATUSES[self.status]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :places
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def after_sign_in_path_for(resource_or_scope)
    places_path
  end
end

app/controllers/gallery_images_controller.rb
class GalleryImagesController < ApplicationController
  respond_to :js

  def create
    @gallery_image = GalleryImage.new(params[:gallery_image])

    if @gallery_image.save
      respond_with @gallery_image
    else
      
    end
  end

  def destroy
    gallery_image = GalleryImage.find(params[:id])
    gallery_image.destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = current_user.places
  end

  def show
    @place = Place.find(params[:id])
    @service = Service.new
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(params[:place])
    @place.user_id = current_user.id

    if @place.save
      respond_to do |format|
        format.html { redirect_to place_path(@place), notice: 'Place created successfully!'}
        format.js
      end
    else
      format.html { render :new}
    end
  end

  def edit
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])

    if @place.update_attributes(params[:place])
      respond_to do |format|
        format.html { redirect_to place_path(@place), notice: 'Place updated successfully!' }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.js
      end
    end
  end

  def destroy
    @place = Place.find(params[:id])

    if @place.destroy
      respond_to do |format|
        format.html { redirect_to places_path, notice: 'Place deleted successfully!'}
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to places_path, error: 'Error occurred!!'}
        format.js
      end
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  respond_to :js
  def new
    @service = Service.new
  end

  def create
    @service = Service.new(params[:service])

    if @service.save
      respond_with @service
    else
      render 
    end
  end

  def destroy
    service = Service.find(params[:id])
    @place = service.place

    if service.destroy
      respond_with @place
    else
      
    end
  end

  def edit
    @service = Service.find(params[:id])
    respond_with @service
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_images_helper.rb
module GalleryImagesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/gallery_images/create.js.erb
$('#gallery-thumbnails').append('<%= escape_javascript render 'places/gallery_thumb_item', image: @gallery_image %>');
$("#gallery-image-form")[0].reset();

app/views/gallery_images/destroy.js.erb
$('.delete-image').bind('ajax:success', function(){
  $(this).closest('li').remove();
});

app/views/home/index.html.haml
.hero-unit
  %h1 Welcome to Camper!
  %p This app connects people who want to find great places for leisure with those who offer such services. 
  = link_to 'Sign Up Here', new_user_registration_path, class: 'btn'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Camper"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")
    = javascript_include_tag "application"

  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Camper', root_url, class: 'brand'
          .container.nav-collapse
            %ul.nav
              %li= link_to "Places", "#"
              %li= link_to "My Account", edit_user_registration_path
              - if current_user
                %li= link_to "Log out", destroy_user_session_path, method: :delete

    .container-fluid

      .row-fluid
        = yield(:sidebar)
        .span10
          = bootstrap_flash
          = yield
    
      %footer
        %p &copy; Maris Cilitis 2013
   

app/views/places/_form.html.haml
= form_for(place, html: { class: 'form-horizontal' }) do |f|
  %fieldset
    %legend
      = "#{controller.action_name.capitalize} Place" 
    .control-group
      = f.label :name, class: 'control-label'
      .controls
        = f.text_field :name
    .control-group
      = f.label :description, class: 'control-label'
      .controls
        = f.text_area :description, rows: 4
    .control-group
      = f.label :status, class: 'control-label'
      .controls
        = f.select :status, options_for_select([['Published', 1], ['Draft', 0]])
    .control-group
    - unless @place.new_record?
      .control-group
        .controls
          = f.file_field :image
      .control-group
        = f.label :location, class: 'control-label'
        .controls
          = f.select :location_id, options_from_collection_for_select(Location.avaliable_locations_for_select, "id", "name")
    .controls
      = f.submit 'Submit', class: 'btn'

app/views/places/_gallery_image_list.html.haml
- images = place.gallery_images
- if images.any?
  - images.each do |image|
    = render 'gallery_thumb_item', image: image
-else
  %span Your place does not have any gallery images added yet!

app/views/places/_gallery_thumb_item.html.haml
%li
  = link_to(image_tag(image.image.thumb.url), image.image.main.url, class: 'thumbnail gallery', rel: 'group1')
  %span.actions
    = link_to 'edit', '#'
    = link_to 'delete', gallery_image_path(image), method: :delete, confirm: 'Are you sure?', class: 'delete-image', remote: true

app/views/places/_place.html.haml
%tr
  %td= link_to place.name, place_path(place)
  %td= place.status
  %td= place.created_at.to_date
  %td
    = link_to 'Edit', edit_place_path(place)
    = link_to 'Delete', place_path(place), method: :delete, confirm: 'Are you sure?'

app/views/places/edit.html.haml
- content_for(:sidebar) do 
  = render 'shared/sidebar'
.span10
  = render 'form', place: @place

app/views/places/index.html.haml
- content_for(:sidebar) do 
  = render 'shared/sidebar'
.span10
  %h1 Your Places!
  - if current_user.places.any?
    %table.table.table-striped
      %thead
        %tr
          %th Name
          %th Status
          %th Created At
          %th Actions
      = render @places
  - else
    %p Looks like you dont have any places added yet!
    = link_to 'Add new place...', new_place_path, class: 'btn'

app/views/places/new.html.haml
- content_for(:sidebar) do 
  = render 'shared/sidebar'
.span10
  = render 'form', place: @place

app/views/places/show.html.haml
- content_for(:sidebar) do
  = render 'shared/sidebar'
.container.place
  %h1= @place.name
  %ul.nav.nav-tabs
    %li.active= link_to 'Place Information', "#place-information", :"data-toggle" => 'tab'
    %li= link_to 'Services', "#service-list", :"data-toggle" => 'tab'
    %li= link_to 'Gallery', "#gallery", :"data-toggle" => 'tab'
  .tab-content
    .tab-pane.active#place-information
      .container
        .header
          %ul.thumbnails
            %li= link_to(image_tag(@place.image.thumb.url), @place.image.main.url, class: 'thumbnail', id: 'title-image')
          .edit-link
            = link_to 'edit place', edit_place_path(@place)
        .attr-section
          %span.title Description
          %span.content= @place.description
        .attr-section
          %span.title Location
          %span.content= @place.location_name
        .attr-section
          %span.title Services
          %span.content
            Currently offering 
            = link_to "#{@place.services.count} services!", '#'
    .tab-pane#service-list
      = render 'services/service_list', services: @place.services
    .tab-pane#gallery
      .container
        #gallery-upload
          = form_for(GalleryImage.new, html: { class: 'form-horizontal' ,id: 'gallery-image-form', multipart: true }, remote: true ) do |f|
            %fieldset
              %legend Upload image to your gallery
              .control-group
                = label_tag :image, "Image", class: 'control-label'
                .controls
                  = f.file_field :image
                = f.hidden_field :place_id, value: @place.id
              .controls
                = f.submit 'Upload', class: 'btn'
        %ul.thumbnails#gallery-thumbnails
          = render 'gallery_image_list', place: @place

.modal.hide.fade#serviceModal
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3= "New Service For: #{@place.name}"
  .modal-body#modal-form
    = form_for(@service, html: { class: 'form-horizontal' ,id: 'service-form', multipart: true }, remote: true ) do |f|
      %fieldset
        %legend Service details
        .control-group
          = f.label :name, "Name",class: 'control-label'
          .controls
            = f.text_field :name
        .control-group
          = f.label :description, "Description", class: 'control-label'
          .controls
            = f.text_area :description, rows: 4 
        .control-group
          = f.label :price,"Price", class: 'control-label'
          .controls
            = f.text_field :price
        .control-group
          = label_tag :image, "Image", class: 'control-label'
          .controls
            = f.file_field :image
        .control-group
          = f.label :status, "Status", class: 'control-label'
          .controls
            = f.select :status, options_for_select([["Published",1], ["Draft", 0], ["Unavaliable", 2]])
          = f.hidden_field :place_id, value: @place.id
        .controls
          = f.submit 'Submit', class: 'btn'
  .modal-footer
    %a.btn{:href => "#"} Close
    %a.btn.btn-primary{:href => "#"} Save changes

.modal.hide.fade#galleryImageModal
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3= "New Service For: #{@place.name}"
  .modal-body#modal-form
    = form_for(@service, html: { class: 'form-horizontal' ,id: 'service-form', multipart: true }, remote: true ) do |f|
      %fieldset
        %legend Service details
        .control-group
          = f.label :name, "Name",class: 'control-label'
          .controls
            = f.text_field :name
        .control-group
          = f.label :description, "Description", class: 'control-label'
          .controls
            = f.text_area :description, rows: 4 
        .control-group
          = f.label :price,"Price", class: 'control-label'
          .controls
            = f.text_field :price
        .control-group
          = label_tag :image, "Image", class: 'control-label'
          .controls
            = f.file_field :image
        .control-group
          = f.label :status, "Status", class: 'control-label'
          .controls
            = f.select :status, options_for_select([["Published",1], ["Draft", 0], ["Unavaliable", 2]])
          = f.hidden_field :place_id, value: @place.id
        .controls
          = f.submit 'Submit', class: 'btn'
  .modal-footer
    %a.btn{:href => "#"} Close
    %a.btn.btn-primary{:href => "#"} Save changes
:javascript
  $(document).ready(function() {
    $("a#title-image").fancybox();
    $('a.gallery').fancybox();
  });

app/views/services/_service_list.html.haml
%h3 Service list
- if services.empty?
  %span#no-services-notice
    You dont have any services! Your can add them 
    = link_to 'here', '#serviceModal', role: 'button', :"data-toggle" => "modal"
- else
  = link_to 'Add New', '#serviceModal', role: 'button', :"data-toggle" => "modal", class: 'btn'
  %table.table
    %thead
      %tr
        %th Image
        %th Name
        %th Price
        %th Status
        %th Created at
        %th Actions
    - services.each do |service|
      %tr
        %td= image_tag(service.image.mini_thumb.url)
        %td= service.name
        %td= service.price
        %td= service.status_name
        %td= service.created_at.to_date
        %td
          = link_to 'delete', service_path(service), method: :delete, confirm: 'Are you sure?', remote: true, class: 'delete-item'
          = link_to 'edit', edit_service_path(service), remote: true

app/views/services/_service_modal.html.haml
.modal.hide.fade#serviceModal
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3= "New Service For: #{place.name}"
  .modal-body#modal-form
    = form_for(service, html: { class: 'form-horizontal' ,id: 'service-form', multipart: true }, remote: true ) do |f|
      %fieldset
        %legend Service details
        .control-group
          = f.label :name, "Name",class: 'control-label'
          .controls
            = f.text_field :name
        .control-group
          = f.label :description, "Description", class: 'control-label'
          .controls
            = f.text_area :description, rows: 4 
        .control-group
          = f.label :price,"Price", class: 'control-label'
          .controls
            = f.text_field :price
        .control-group
          = label_tag :image, "Image", class: 'control-label'
          .controls
            = f.file_field :image
        .control-group
          = f.label :status, "Status", class: 'control-label'
          .controls
            = f.select :status, options_for_select([["Published",1], ["Draft", 0], ["Unavailable", 2]])
          = f.hidden_field :place_id, value: place.id
        .controls
          = f.submit 'Submit', class: 'btn'
  .modal-footer
    %a.btn{:href => "#"} Close
    %a.btn.btn-primary{:href => "#"} Save changes

app/views/services/create.js.erb
$('#service-list').html('<%= escape_javascript render 'services/service_list', services: @service.place.services %>');
$('#serviceModal').modal('hide');
$("#service-form")[0].reset();

app/views/services/edit.js.erb
$('#myModal').modal('show');

app/views/shared/_sidebar.html.haml
.span2
  .well.sidebar-nav
    %ul.nav.nav-list
      %li.nav-header Sidebar
      %li= link_to "My Places", places_path
      %li= link_to "Add new place", new_place_path
      %li= link_to "Link 3", "/path3"